---

- hosts: ubuntu1904
  tasks:
    - name: Copy file from master to ubuntu1904
      copy: src=. dest=/tmp/zrythm-installer

    - name: Ensure dependencies are installed
      become: yes
      apt:
        name: ['libgtk-3-dev', 'libjack-jackd2-dev',
        'liblilv-dev', 'libsndfile1-dev', 'ninja-build',
        'help2man', 'python3-sphinx', 'qtbase5-dev',
        'libasound2-dev', 'libavcodec-dev', 'portaudio19-dev',
        'ladspa-sdk', 'libfftw3-dev', 'lv2-dev',
        'libsamplerate0-dev', 'libavformat-dev', 'libyaml-dev']
        update_cache: yes
        state: present

    - name: Make Ubuntu 19.04 build
      shell: cd /tmp/zrythm-installer && make clean && make ubuntu1904

    - name: Deploy artifacts
      fetch: src=/tmp/zrythm-installer/build/debian10/zrythm_{{ version }}-1_amd64.deb dest=./artifacts/ubuntu1904/zrythm_{{ version }}-1_amd64.deb flat=yes

- hosts: debian10
  tasks:
    - name: Copy file from master to debian10
      copy: src=. dest=/tmp/zrythm-installer

    - name: Ensure dependencies are installed
      become: yes
      apt:
        name: ['libgtk-3-dev', 'libjack-jackd2-dev',
        'liblilv-dev', 'libsndfile1-dev', 'ninja-build',
        'help2man', 'python3-sphinx', 'qtbase5-dev',
        'libasound2-dev', 'libavcodec-dev', 'portaudio19-dev',
        'ladspa-sdk', 'libfftw3-dev', 'lv2-dev',
        'libsamplerate0-dev', 'libavformat-dev', 'libyaml-dev']
        update_cache: yes
        state: present

    - name: Make Debian 10 build
      shell: cd /tmp/zrythm-installer && make clean && make debian10
      register: results

    - name: show results
      debug: msg={{ results.stdout_lines }}

    - name: Deploy artifacts
      fetch: src=/tmp/zrythm-installer/build/debian10/zrythm_{{ version }}-1_amd64.deb dest=./artifacts/debian10/zrythm_{{ version }}-1_amd64.deb flat=yes
