---

- name: Copy package definitions from master
  copy:
    src: "{{ item }}"
    dest: /tmp/zrythm-installer/
  with_fileglob:
    - "{{ playbook_dir }}/*"

- name: Copy tarballs from master
  copy:
    src: "{{ item }}"
    dest: /tmp/zrythm-installer/build/
  with_fileglob:
    - "{{ playbook_dir }}/build/zrythm-{{ version }}.tar.xz*"
    - "{{ playbook_dir }}/build/zplugins-{{ zplugins_version }}.tar.gz"
    - "{{ playbook_dir }}/build/meson-{{ meson_version }}.tar.gz"
