---

- name: Prepare
  include_tasks: "{{ playbook_dir }}/tasks/prepare_ubuntu.yml"
  when: inventory_hostname == 'linuxmint193' or
        inventory_hostname == 'ubuntu1804' or
        inventory_hostname == 'ubuntu1810' or
        inventory_hostname == 'ubuntu1904' or
        inventory_hostname == 'ubuntu1910' or
        inventory_hostname == 'debian10'

- name: Prepare no guile
  include_tasks: "{{ playbook_dir }}/tasks/prepare_ubuntu_noguile.yml"
  when: inventory_hostname == 'debian9'

- name: Make build
  shell: |
    cd /tmp/zrythm-installer
    make clean
    make {{ inventory_hostname }}

- name: Make AppImage
  shell: |
    cd /tmp/zrythm-installer
    make build/Zrythm-{{ version }}-x86_64.AppImage
    make build/Zrythm-trial-{{ version }}-x86_64.AppImage
  when: inventory_hostname == 'debian9'

- name: Deploy artifacts
  include_tasks: "{{ playbook_dir }}/tasks/ubuntu_deploy.yml"
