---

- name: Zip plugins
  shell: |
    cd /tmp/zrythm-installer/build &&
    rm -rf zplugins* &&
    mkdir zplugins-trial &&
    mkdir zplugins
    mv Z*-trial.lv2 zplugins-trial/ &&
    mv Z*.lv2 zplugins/ &&
    zip -r zplugins.zip zplugins &&
    zip -r zplugins-trial.zip zplugins-trial

- name: Deploy plugins
  fetch: src=/tmp/zrythm-installer/build/zplugins.zip dest=./artifacts/{{ inventory_hostname }}/zplugins.zip flat=yes

- name: Deploy plugins
  fetch: src=/tmp/zrythm-installer/build/zplugins-trial.zip dest=./artifacts/{{ inventory_hostname }}/zplugins-trial.zip flat=yes
