---

- name: Zip manuals
  shell: |
    cd /tmp/zrythm-installer/build/zrythm-{{ version }} &&
    cd build/doc/user &&
    rm -rf user-manual.zip &&
    mv en/latex/Zrythm.pdf Zrythm-en.pdf &&
    mv fr/latex/Zrythm.pdf Zrythm-fr.pdf &&
    mv de/latex/Zrythm.pdf Zrythm-de.pdf &&
    zip -r user-manual.zip Zrythm-fr.pdf Zrythm-en.pdf Zrythm-de.pdf

- name: Deploy manuals
  fetch: src=/tmp/zrythm-installer/build/zrythm-{{ version }}/build/doc/user/user-manual.zip dest=./artifacts/{{ inventory_hostname }}/user-manual.zip flat=yes
