---

- name: Install latest lv2 and suil
  shell: |
    cd /home/ansible/
    wget http://download.drobilla.net/suil-0.10.6.tar.bz2
    wget http://download.drobilla.net/lilv-0.24.6.tar.bz2
    wget http://download.drobilla.net/serd-0.30.2.tar.bz2
    wget http://download.drobilla.net/sratom-0.6.4.tar.bz2
    wget http://download.drobilla.net/sord-0.16.4.tar.bz2
    wget http://lv2plug.in/spec/lv2-1.16.0.tar.bz2
    tar xf lv2-1.16.0.tar.bz2
    tar xf lilv-0.24.6.tar.bz2
    tar xf suil-0.10.6.tar.bz2
    tar xf serd-0.30.2.tar.bz2
    tar xf sord-0.16.4.tar.bz2
    tar xf sratom-0.6.4.tar.bz2
    cd /home/ansible/lv2-1.16.0
    python3 ./waf configure
    python3 ./waf
    sudo python3 ./waf install
    cd /home/ansible/sord-0.16.4
    python3 ./waf configure --static --no-shared --no-utils
    python3 ./waf
    sudo python3 ./waf install
    cd /home/ansible/suil-0.10.6
    python3 ./waf configure --static --no-shared
    python3 ./waf
    sudo python3 ./waf install
    cd /home/ansible/serd-0.30.2
    python3 ./waf configure --static --no-shared
    python3 ./waf
    sudo python3 ./waf install
    cd /home/ansible/sratom-0.6.4
    python3 ./waf configure --static --no-shared
    python3 ./waf
    sudo python3 ./waf install
    cd /home/ansible/lilv-0.24.6
    python3 ./waf configure --static --no-shared --no-utils
    python3 ./waf
    sudo python3 ./waf install
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
