---

- name: Deploy normal version
  fetch: src=/tmp/zrythm-installer/build/debian10/zrythm_{{ version }}-1_amd64.deb dest=./artifacts/{{ inventory_hostname }}/zrythm_{{ version }}-1_amd64.deb flat=yes

- name: Deploy trial
  fetch: src=/tmp/zrythm-installer/build/debian10/zrythm-trial_{{ version }}-1_amd64.deb dest=./artifacts/{{ inventory_hostname }}/zrythm-trial_{{ version }}-1_amd64.deb flat=yes

- name: Zip and deploy ZLFO
  include_tasks: "{{ playbook_dir }}/tasks/deploy_zlfo.yml"
